# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Firebase App distribution"
  lane :distribute do
        sh("flutter clean")
        sh("flutter pub get")
        sh("flutter build apk --flavor Production -t lib/main_production.dart --release")
        firebase_app_distribution(
        app: "1:218333851185:android:3aece708bc8177e9182f10",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        release_notes: "This is a new version to test the app",
        testers: "khaledmokhaled123@gmail.com")
  end
end
